export const BUTTONS = [
    {value: "C"},
    {value: "Off"},
    {value: 1},
    {value: "+"},
    {value: 2},
    {value: 3},
    {value: 4},
    {value: "-"},
    {value: 5},
    {value: 6},
    {value: 7},
    {value: "/"},
    {value: 8},
    {value: 9},
    {value: 0},
    {value: "*"},
    {value: "%"},
    {value: "√"},
    {value: "."},
    {value: "="},
];
